<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>AgeAnalysis</name>
  <uuid>83f61317-b44e-4235-b22a-bd74848a4c65</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Age is at least 18 and less than 55
then
    set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
