<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>54772642-b59b-4e96-b812-49ed3b2ea91c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "No puede tener prestamos pre aprobados" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
