<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ed458594-2970-417e-999e-008d37f54915</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0.55 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
