<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RiskAnalysis</name>
  <uuid>76ce0835-49cd-4d91-9702-b3af2f4b406f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Employment is dependiente then
    set decision to 0.2 ;


]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
