<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RiskAnalysis2</name>
  <uuid>2b457a9a-4e3e-4625-93c3-36addaff4dc9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Employment is independiente then
    set decision to 0.4 ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
