<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>AnalysisIncome</name>
  <uuid>54ae958d-b63a-497b-8891-b16219b12c96</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Income is at least 1500
then
    set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
