<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ExecuteModel</name>
  <uuid>660eeeb8-b6aa-4fd0-aa33-ed7db542a704</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the risk decision model computed from
      Input type being employment_var;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
