<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>SetData</name>
  <uuid>13d0f89d-7764-4287-ad0c-651a9bdf62bb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
        the age is 25, 
        the balance is 150, 
        the campaign is 1, 
        the contact is "email", 
        the day is 21, 
        the default is "no", 
        the duration is 75, 
        the education is "school", 
        the housing is "no", 
        the job is "no", 
        the loan is "no", 
        the marital is "single", 
        the month is "oct", 
        the pdays is -1, 
        the poutcome is "no", 
        the previous is 1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
