<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7ac9c8ae-a60f-4f2f-aafa-891df143609e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0.5 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
