<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RiskAnalysis2</name>
  <uuid>fbf3f36a-cec0-46f7-b9eb-b7714551efbb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Employment is independiente 
then
    set decision to 0.4 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
