<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RiskAnalysis3</name>
  <uuid>5149767b-75a6-4610-b6d2-78877cf43c82</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Employment is sin empleo then
 set decision to 0.8 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
