<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RiskAnalysis1</name>
  <uuid>476c8663-72e0-451c-aaf9-e0a571267a68</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Employment is dependiente
then
    set decision to 0.2 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
